name: Start_monitoreo

on:
  schedule:
    - cron: '0 * * * *'  
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python     
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' 

      - name: Install dependencies
        run: 
           pip install --upgrade pip 
           pip install telegram  
           pip install python-telegram-bot
        
      - name: Run script    
        run: python ./NslookupServidores.py 
