name: Start_monitoreo

on:
  push:
    branches: [main]
    
  schedule:
    - cron: '0 * * * *'  
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python     
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install dependencies
        run: 
           pip install anyio
           pip install certifi
           pip install h11
           pip install httpcore
           pip install httpx
           pip install idna
           pip install python-telegram-bot
           pip install requests
           pip install setuptools
           pip install sniffio
           pip install telegram  
          
        
      - name: Run script    
        run: python ./NslookupServidores.py 
